import { categories, Data, Entry, paymentCategories } from "./finance";

export const tableNames = [
  "categories",
  "credit_cards",
  "payments",
  "incomes",
  "recurrences",
  "installment_plans",
  "monthly_overrides",
] as const;
export type TableName = (typeof tableNames)[number];
export type Row = {
  id: string;
  [key: string]: string | number | boolean | null;
};
export type Tables = Record<TableName, Row[]>;
export type Changes = Record<TableName, { upsert: Row[]; remove: string[] }>;
export type Snapshot = {
  revision: number;
  initialized: boolean;
  tables: Tables;
};
export const emptyData = (): Data => ({
  categories: [...categories],
  payments: [],
  incomes: [],
  overrides: {},
});
export const emptyTables = (): Tables =>
  Object.fromEntries(tableNames.map((t) => [t, []])) as unknown as Tables;

// The domain model stays independent of SQL; JSON is only the RPC transport.
export function toTables(data: Data): Tables {
  const result = emptyTables();
  result.categories = paymentCategories(data).map((name, position) => ({
    id: name,
    name,
    position,
  }));
  const cards = new Set<string>();
  for (const [kind, entries] of [
    ["payment", data.payments],
    ["income", data.incomes],
  ] as const) {
    for (const [position, e] of entries.entries()) {
      if (kind === "payment" && e.card) cards.add(e.card);
      const row: Row = {
        id: e.id,
        name: e.name,
        amount: e.amount,
        currency: e.currency,
        due_date: e.date,
        status: e.status,
        notes: e.notes,
        variable: e.variable,
        end_month: e.end ?? null,
        position,
      };
      if (kind === "payment") {
        row.category_id = e.category;
        row.card_id = e.card || null;
      }
      result[kind === "payment" ? "payments" : "incomes"].push(row);
      if (e.interval)
        result.recurrences.push({
          id: `${kind}:${e.id}`,
          payment_id: kind === "payment" ? e.id : null,
          income_id: kind === "income" ? e.id : null,
          interval_months: e.interval,
        });
      if (e.installments) {
        if (kind === "income")
          throw new Error("Un ingreso no puede tener cuotas de compra.");
        result.installment_plans.push({
          id: e.id,
          payment_id: e.id,
          total_installments: e.installments,
        });
      }
    }
  }
  for (const [id, o] of Object.entries(data.overrides)) {
    if (!o) continue; // Ignore the obsolete placeholder generated by early prototypes.
    const split = id.lastIndexOf(":");
    const entryId = id.slice(0, split),
      month = id.slice(split + 1);
    const payment = data.payments.some((e) => e.id === entryId);
    if (!payment && !data.incomes.some((e) => e.id === entryId))
      throw new Error(
        `La excepción ${id} no tiene un pago o ingreso asociado.`,
      );
    if (payment && o.card) cards.add(o.card);
    result.monthly_overrides.push({
      id,
      payment_id: payment ? entryId : null,
      income_id: payment ? null : entryId,
      month,
      name: o.name ?? null,
      amount: o.amount ?? null,
      currency: o.currency ?? null,
      category_id: payment ? (o.category ?? null) : null,
      due_date: o.date ?? null,
      status: o.status ?? null,
      interval_months: o.interval ?? null,
      variable: o.variable ?? null,
      notes: o.notes ?? null,
      end_month: o.end ?? null,
      card_id: payment ? o.card || null : null,
      total_installments: o.installments ?? null,
    });
  }
  result.credit_cards = [...cards].map((name) => ({ id: name, name }));
  return result;
}

export function fromTables(tables: Tables): Data {
  const overrides: Data["overrides"] = {};
  const ordered = (rows: Row[]) =>
    [...rows].sort((a, b) => Number(a.position) - Number(b.position));
  function entries(kind: "payment" | "income"): Entry[] {
    return ordered(tables[kind === "payment" ? "payments" : "incomes"]).map(
      (r) => {
        const recurrence = tables.recurrences.find(
          (x) => x[`${kind}_id`] === r.id,
        );
        const installments =
          kind === "payment"
            ? tables.installment_plans.find((x) => x.payment_id === r.id)
            : undefined;
        return {
          id: r.id,
          name: String(r.name),
          amount: Number(r.amount),
          currency: r.currency as Entry["currency"],
          category: kind === "payment" ? String(r.category_id) : "Ingreso",
          date: String(r.due_date),
          status: String(r.status),
          interval: Number(recurrence?.interval_months ?? 0),
          variable: Boolean(r.variable),
          notes: String(r.notes),
          ...(r.end_month ? { end: String(r.end_month) } : {}),
          ...(r.card_id ? { card: String(r.card_id) } : {}),
          ...(installments
            ? { installments: Number(installments.total_installments) }
            : {}),
        };
      },
    );
  }
  const mapping = {
    name: "name",
    amount: "amount",
    currency: "currency",
    category_id: "category",
    due_date: "date",
    status: "status",
    interval_months: "interval",
    variable: "variable",
    notes: "notes",
    end_month: "end",
    card_id: "card",
    total_installments: "installments",
  } as const;
  for (const r of tables.monthly_overrides) {
    const o: Record<string, unknown> = {};
    for (const [column, key] of Object.entries(mapping))
      if (r[column] !== null && r[column] !== undefined)
        o[key] = ["amount", "interval", "installments"].includes(key)
          ? Number(r[column])
          : r[column];
    overrides[`${r.payment_id ?? r.income_id}:${r.month}`] =
      o as Partial<Entry>;
  }
  return {
    categories: ordered(tables.categories).map((r) => String(r.name)),
    payments: entries("payment"),
    incomes: entries("income"),
    overrides,
  };
}

function sameRow(a: Row, b: Row) {
  return (
    Object.keys(a).length === Object.keys(b).length &&
    Object.entries(a).every(([k, v]) => b[k] === v)
  );
}
export function diffTables(before: Tables, after: Tables): Changes {
  return Object.fromEntries(
    tableNames.map((table) => {
      const old = new Map(before[table].map((r) => [r.id, r]));
      const next = new Set(after[table].map((r) => r.id));
      return [
        table,
        {
          upsert: after[table].filter(
            (r) => !old.has(r.id) || !sameRow(old.get(r.id)!, r),
          ),
          remove: before[table].filter((r) => !next.has(r.id)).map((r) => r.id),
        },
      ];
    }),
  ) as Changes;
}
